# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
docs/openapi.yaml:
  no-unused-components:
      # the created response's headers are used but
      # since the bodies are not empty, the entire
      # response is not used anywhere. However, for consistency
      # and to keep the individual responses DRY, we want
      # to keep the 201 in the root openapi file, so we
      # disable the unused component rule for this response
    - '#/components/responses/201'
