extends:
  - spectral:oas
  # note this only covers the 2019 top ten https://github.com/stoplightio/spectral-owasp-ruleset/issues/47
  - https://unpkg.com/@stoplight/spectral-owasp-ruleset/dist/ruleset.mjs
rules:
  # override a couple of rules that erroneously apply to HEAD requests
  "owasp:api3:2019-define-error-responses-500":
    message: "Operation is missing {{property}}."
    description: OWASP API Security recommends defining schemas for all responses, even errors. The 500 describes what happens when a request fails with an internal server error, so its important to define this not just for documentation, but to empower contract testing to make sure the proper JSON structure is being returned instead of leaking implementation details in backtraces.
    given: $.paths.*[get,put,post,patch,delete].responses
    then:
      - field: "500"
        function: truthy
      - field: "500.content"
        function: truthy

  "owasp:api3:2019-define-error-responses-401":
    message: "Operation is missing {{property}}."
    description: "OWASP API Security recommends defining schemas for all responses, even errors. The 401 describes what happens when a request is unauthorized, so its important to define this not just for documentation, but to empower contract testing to make sure the proper JSON structure is being returned instead of leaking implementation details in backtraces."
    given: $.paths.*[get,put,post,patch,delete].responses
    then:
      - field: "401"
        function: truthy
      - field: "401.content"
        function: truthy


  "should-have-422":
    message: "Operation is missing {{property}}."
    description: ""
    given: $.paths.*[put,post,patch].responses
    then:
      - field: "422"
        function: truthy
      - field: "422.content.application/problem+json"
        function: truthy