name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - 1.0.0*
  pull_request:
    branches:
      - 1.0.0*

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v5
        with:
          incremental_files_only: false
          config: 'cspell.json'
          # eventually we intend to fail the build on spelling errors
          # so we restrict this to the docs folder
          root: './docs'
          # only warn for now
          inline: warning # error
          strict: false # true fails the build
